swagger: '2.0'
info:
  description: |
    uCargo A.P.I. Version 1.0
    out more about Swagger at 
    [http://swagger.io](http://swagger.io) or on 
    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  version: 1.0.0
  title: uCargo A.P.I. Version 1.0
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: user
    description: Everything about your user
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
paths:
  /api/v1/drivers/account:
    x-swagger-router-controller: driver
    post:
      tags:
        - driver
      description: signin to uCargo
      parameters:
        - name: signin
          in: body
          required: true
          schema:
            $ref: '#/definitions/SigninRequest'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Error 400
          schema:
            $ref: '#/definitions/ApiResponse'
    get:
      tags:
        - driver
      description: login to uCargo
      parameters:
        - name: Authorization
          in: header
          description: Http Basic Auth
          required: true
          type: string
          format: string
          default: Basic QWxhZGRpbjpPcGVuU2VzYW1l
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/LoginResponse'
        '401':
          description: Error 401 Unauthorized
          schema:
            $ref: '#/definitions/ApiResponse'
    patch:
      tags:
        - driver
      description: Update for uCargo driver
      parameters:
        - name: x-auth-token
          in: header
          description: token obtenido del login
          required: true
          type: string
          format: string
        - name: x-api-key
          in: header
          description: API key
          required: true
          type: string
          format: string
          default: e70e918f-8035-48fc-a707-4507e1fd85c1
        - name: update
          in: body
          required: true
          schema:
            $ref: '#/definitions/SigninRequest'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Error 400
          schema:
            $ref: '#/definitions/ApiResponse'
definitions:
  SigninRequest:
    title: RequestSignin
    type: object
    properties:
      account:
        type: object
        properties:
          email:
            type: string
          password:
            type: string
          username:
            type: string
          name:
            type: string
          picture:
            type: string
    example:
      account:
        email: driver@dominio.com
        username: test
        name: test
        picture: picture_path
  LoginRequest:
    title: RequestLogin
    type: object
    properties:
      account:
        type: object
        properties:
          username:
            type: string
          password:
            type: string
    example:
      account:
        username: driver1
        password: test1234!
  LoginResponse:
    title: SuccessLoginResponse
    type: object
    properties:
      account:
        type: object
        properties:
          token:
            type: string
          email:
            type: string
          username:
            type: string
          name:
            type: string
          picture:
            type: string
    example:
      account:
        token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1Y2FyZ28iLCJleHAiOjE1MjAyMTg1MTcsImlhdCI6MTUxNzc5OTMxNywiaXNzIjoidWNhcmdvIiwianRpIjoiMjM5YWE3YmEtMWIxMC00NTVjLWIzMGQtZjY5Mjk4ZWNmNzJhIiwibmJmIjoxNTE3Nzk5MzE2LCJzdWIiOiIxIiwidHlwIjoiYWNjZXNzIn0.riUHO7W-l42U9WhQC1ZC5DPNlNCkhULG-tcvVraTjAGjaX49wLwIaKa2FpzzCXtfrzVq0OJj8zgYABIHQ8PRsA
        email: driver@dominio.com
        username: test
        name: test
        picture: picture_path
  ApiResponse:
    type: object
    properties:
      error:
        type: string
    example:
      error: Email or password is incorrect
  ApiBadResponse:
    type: object
    properties:
      error:
        type: string
    example:
      error: Bloked
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
host: virtserver.swaggerhub.com
schemes:
  - https
  - http
basePath: /ucargo/ucargo/1.0.0
